import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, TrendingUp, Brain, Award } from "lucide-react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";

const trendData = [
  { day: "Mon", Resolved: 24, Open: 8 },
  { day: "Tue", Resolved: 29, Open: 5 },
  { day: "Wed", Resolved: 31, Open: 6 },
  { day: "Thu", Resolved: 28, Open: 10 },
  { day: "Fri", Resolved: 33, Open: 7 },
  { day: "Sat", Resolved: 20, Open: 12 },
  { day: "Sun", Resolved: 25, Open: 9 }
];

const leaderboard = [
  { name: "Sarah Lopez", resolved: 42, avg_time: "2.5 min" },
  { name: "Marcus Lee", resolved: 39, avg_time: "3.1 min" },
  { name: "Emma Rodriguez", resolved: 35, avg_time: "3.3 min" }
];

export const AIReports = () => {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-2">
        <h1 className="text-2xl font-semibold text-foreground">AI Reports</h1>
        <p className="text-sm text-muted-foreground">
          Automated analytics and performance predictions generated by QueryBot AI.
        </p>
      </div>

      {/* Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-in">
        {/* AI Summary Overview */}
        <Card className="border-primary/25 shadow-[0_0_16px_rgba(163,123,255,0.15)] hover:scale-[1.02] transition-all duration-300" style={{ animationDelay: "0s" }}>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Activity className="h-5 w-5 text-primary" />
              <CardTitle>AI Summary Overview</CardTitle>
            </div>
            <CardDescription>
              Automated insights from system performance and technician activity.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Active Tickets</p>
                <p className="text-2xl font-bold text-primary">32</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Avg Response Time</p>
                <p className="text-2xl font-bold text-primary">2.8 min</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">Resolution Rate</p>
                <p className="text-2xl font-bold text-primary">96.4%</p>
              </div>
              <div className="space-y-1">
                <p className="text-sm text-muted-foreground">AI Confidence</p>
                <p className="text-2xl font-bold text-primary">89%</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Ticket Resolution Trends */}
        <Card className="border-primary/25 shadow-[0_0_16px_rgba(163,123,255,0.15)] hover:scale-[1.02] transition-all duration-300" style={{ animationDelay: "0.1s" }}>
          <CardHeader>
            <div className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              <CardTitle>Ticket Resolution Trends</CardTitle>
            </div>
            <CardDescription>Resolved vs Open Tickets (Last 7 Days)</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-[200px] w-full bg-background/40 rounded-lg p-2">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={trendData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(163,123,255,0.1)" />
                  <XAxis 
                    dataKey="day" 
                    stroke="#A37BFF" 
                    style={{ fontSize: '12px' }}
                  />
                  <YAxis 
                    stroke="#A37BFF" 
                    style={{ fontSize: '12px' }}
                  />
                  <Tooltip 
                    contentStyle={{ 
                      background: 'rgba(20,10,40,0.95)', 
                      border: '1px solid rgba(163,123,255,0.25)',
                      borderRadius: '8px',
                      color: '#FFFFFF'
                    }}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="Resolved" 
                    stroke="#A37BFF" 
                    strokeWidth={2}
                    dot={{ fill: '#A37BFF' }}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="Open" 
                    stroke="#7D5CFF" 
                    strokeWidth={2}
                    dot={{ fill: '#7D5CFF' }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>

        {/* AI Prediction Insights */}
        <Card className="border-primary/25 shadow-[0_0_16px_rgba(163,123,255,0.15)] hover:scale-[1.02] transition-all duration-300" style={{ animationDelay: "0.2s" }}>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Brain className="h-5 w-5 text-primary" />
              <CardTitle>AI Prediction Insights</CardTitle>
            </div>
            <CardDescription>AI-detected risk predictions and forecasted performance</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex items-start gap-3 p-3 rounded-lg bg-primary/10 border border-primary/20">
                <span className="text-xl">🔮</span>
                <p className="text-sm text-foreground">
                  AI predicts a 12% increase in resolved tickets next week.
                </p>
              </div>
              <div className="flex items-start gap-3 p-3 rounded-lg bg-destructive/10 border border-destructive/20">
                <span className="text-xl">⚠️</span>
                <p className="text-sm text-foreground">
                  Server response latency may rise by 5% under current workload.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Technician Leaderboard */}
        <Card className="border-primary/25 shadow-[0_0_16px_rgba(163,123,255,0.15)] hover:scale-[1.02] transition-all duration-300" style={{ animationDelay: "0.3s" }}>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Award className="h-5 w-5 text-primary" />
              <CardTitle>Technician Leaderboard</CardTitle>
            </div>
            <CardDescription>Top performing support agents</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {leaderboard.map((tech, index) => (
                <div 
                  key={tech.name}
                  className="flex items-center justify-between p-3 rounded-lg bg-background/40 border border-primary/10 hover:border-primary/25 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary/20 text-primary font-bold">
                      {index + 1}
                    </div>
                    <div>
                      <p className="font-medium text-foreground">{tech.name}</p>
                      <p className="text-xs text-muted-foreground">Avg: {tech.avg_time}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-lg font-bold text-primary">{tech.resolved}</p>
                    <p className="text-xs text-muted-foreground">Resolved</p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
