// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbcysuaaazyjwucgiydm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiY3lzdWFhYXp5and1Y2dpeWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MjgwNDcsImV4cCI6MjA3NjEwNDA0N30.A7JYVxZQDCWkgSKPbdEamdk0e4zyVlOnOpnspDi0sh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});